chat:
  autoPass: true #是否自动通过好友添加
  proxy: false #是否开启代理
  proxyUrl: http://127.0.0.1:7890
  sessionTimeOut: 60
  model: gpt-4 #模型选择


# 以下为可选配置 画图前缀
mode:
  imagePrefix: 画图：

one-api:
  proxy: #gpt接口地址
  s-token: #gpt token

push:
  url: http://www.pushplus.plus/send
  token: #pushPlus的个人token


discord:
  channelId: #频道ID
  botId: #coze机器人的ID
  sendBotToken: #discord自建机器人的token
  proxyUrl: http://127.0.0.1:7890  #代理地址
  proxyEnable: false #是否开启代理
