chat:
  autoPass: true #是否自动通过好友添加
  proxy: false #是否开启代理
  proxyUrl: http://127.0.0.1:7890
  sessionTimeOut: 60
  model: gpt-4 #模型选择


# 以下为可选配置 画图前缀
mode:
  imagePrefix: 画

one-api:
  proxy: https://one.caifree.com
  s-token: sk-WMNKhCxTzQ1aRl9BB34a3fA005F2422b860bE4F6F8DfE446

push:
  url: http://www.pushplus.plus/send
  token: sk-WMNKhCxTzQ1aRl9BB34a3fA005F2422b860bE4F6F8DfE446


discord:
  channelId: 1202625420994936834
  botId: 1202630278778978315
  sendBotToken: MTIwMjYyNzI3NTg1ODkxMTMwMg.GVbYxQ.GRIK3lwjWnoHV8JGvySYmOTejPeXWmHKEMCQ0E
  proxyUrl: http://127.0.0.1:7890  #代理地址
  proxyEnable: true #是否开启代理
